---
fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    java: "https://github.com/puppetlabs/puppetlabs-java"
    zypprepo: "https://github.com/voxpupuli/puppet-zypprepo.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    systemd: "https://github.com/voxpupuli/puppet-systemd"
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
